Repository boostcampwm-2021/android05-boomerang, pull requests merged in 2021-11, with the labels that each got.

#5 [Feat] DoodleFragment 펜 색상 변경
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodlelight/DrawView.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodlelight/VideoDoodleLightFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodlelight/util/ViewRecorder.java
  app/src/main/res/drawable/background_rb_black.xml
  app/src/main/res/drawable/background_rb_black_selected.xml
  app/src/main/res/drawable/background_rb_black_unselected.xml
  app/src/main/res/drawable/background_rb_blue.xml
  app/src/main/res/drawable/background_rb_blue_selected.xml
  app/src/main/res/drawable/background_rb_blue_unselected.xml
  app/src/main/res/drawable/background_rb_green.xml
  app/src/main/res/drawable/background_rb_green_selected.xml
  app/src/main/res/drawable/background_rb_green_unselected.xml
  app/src/main/res/drawable/background_rb_red.xml
  app/src/main/res/drawable/background_rb_red_selected.xml
  app/src/main/res/drawable/background_rb_red_unselected.xml
  app/src/main/res/drawable/background_rb_yellow.xml
  app/src/main/res/drawable/background_rb_yellow_selected.xml
  app/src/main/res/drawable/background_rb_yellow_unselected.xml
  app/src/main/res/layout/fragment_video_doodle_light.xml
  app/src/main/res/layout/fragment_video_edit_light.xml
Labels: review

#30 [메모 목록 화면] FAB버튼을 누르면 X버튼, 동영상 메모1버튼, 동영상 메모2버튼을 누를 수 있다. #27
  app/build.gradle
  app/src/main/java/com/kotlinisgood/boomerang/ui/home/HomeFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videoselection/VideoSelectionFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/util/Constant.kt
  app/src/main/res/drawable-anydpi/ic_video.xml
  app/src/main/res/drawable-anydpi/ic_video_light.xml
  app/src/main/res/drawable-hdpi/ic_video.png
  app/src/main/res/drawable-hdpi/ic_video_light.png
  app/src/main/res/drawable-mdpi/ic_video.png
  app/src/main/res/drawable-mdpi/ic_video_light.png
  app/src/main/res/drawable-xhdpi/ic_video.png
  app/src/main/res/drawable-xhdpi/ic_video_light.png
  app/src/main/res/drawable-xxhdpi/ic_video.png
  app/src/main/res/drawable-xxhdpi/ic_video_light.png
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/menu/menu_fragment_home_speed_dial.xml
  app/src/main/res/navigation/navigation.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: 기능 추가

#32 Feat: 점 대신 선을 동영상에 그림
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/VideoDoodleFragment.kt
Labels: 기능 추가

#43 [Frame 메모 작성 화면] Capture 버튼 클릭시 발생하는 에러 수정
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/AspectFrameLayout.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/CircularEncoder.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/CircularEncoderBuffer.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/EglCore.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/EglSurfaceBase.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/GlUtil.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/Texture2dProgram.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/VideoDoodleFragment.kt
Labels: bug

#42 Feature/home sort
  app/src/main/java/com/kotlinisgood/boomerang/di/SharedPrefModule.kt
  app/src/main/java/com/kotlinisgood/boomerang/model/OrderState.kt
  app/src/main/java/com/kotlinisgood/boomerang/repository/SharedPrefDataSource.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/home/HomeFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/home/HomeViewModel.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videoselection/VideoSelectionAdapter.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videoselection/VideoSelectionFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/util/Constant.kt
  app/src/main/res/menu/menu_fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: 기능 추가

#45 [메모 목록 화면] 원하는 키워드로 메모를 작성할 수 있다. #40
  app/build.gradle
  app/src/main/java/com/kotlinisgood/boomerang/database/converter/Converter.kt
  app/src/main/java/com/kotlinisgood/boomerang/database/dao/VideoMemoDao.kt
  app/src/main/java/com/kotlinisgood/boomerang/repository/AppRepository.kt
  app/src/main/java/com/kotlinisgood/boomerang/repository/local/LocalDataSource.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/home/HomeFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/home/HomeViewModel.kt
  app/src/main/res/layout/fragment_home.xml
  build.gradle
Labels: 기능 추가

#49 Fix: 재생되는 동영상의 오른쪽 상단이 잘려 저장되는 버그 해결
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/CircularEncoder.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/VideoDoodleFragment.kt
Labels: bug

#50 [Feat] 동영상 메모 화면 UI 개선
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodlelight/SubVideoAdapter.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodlelight/VideoDoodleLightFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodlelight/VideoDoodleLightViewModel.kt
  app/src/main/java/com/kotlinisgood/boomerang/util/BindingUtil.kt
  app/src/main/res/drawable/background_rb_blue_selected.xml
  app/src/main/res/drawable/background_rb_green_selected.xml
  app/src/main/res/drawable/background_rb_red_selected.xml
  app/src/main/res/drawable/background_rb_yellow_selected.xml
  app/src/main/res/drawable/ic_baseline_close_24.xml
  app/src/main/res/drawable/ic_baseline_done_24.xml
  app/src/main/res/drawable/ic_baseline_edit_24.xml
  app/src/main/res/layout/fragment_video_doodle_light.xml
  app/src/main/res/layout/item_rv_doodle_light_subvideos.xml
  app/src/main/res/values/themes.xml
Labels: UI📱

#70 [모두의 메모 작성 화면] 렌더링 과정 개선
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/EglCore.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/EglWindowSurface.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/Texture2dProgram.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/VideoDoodleFragment.kt
Labels: enhancement

#71 [모두의 메모 작성 화면] MediaPlayer 에러 해결
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/VideoDoodleFragment.kt
Labels: bug

#75 [음성 메모 작성 화면] Voice Record Second Fragment 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kotlinisgood/boomerang/ui/voicerecord/SelfReference.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/voicerecord/Voice.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/voicerecord/VoiceRecordFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/voicerecord/VoiceRecordSecondFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/voicerecord/VoiceRecordViewModel.kt
  app/src/main/res/layout/fragment_voice_record.xml
  app/src/main/res/layout/fragment_voice_record_second.xml
  app/src/main/res/navigation/navigation.xml
Labels: 기능 추가

#76 [모두의 메모 작성 화면] Capture 버튼 클릭시 에러 발생 현상 해결
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/CircularEncoder.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/Encoder.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/VideoDoodleFragment.kt
Labels: bug

#78 [음성 메모 작성 화면] 로직 개선
  app/src/main/java/com/kotlinisgood/boomerang/MainActivity.kt
  app/src/main/java/com/kotlinisgood/boomerang/database/AppDatabase.kt
  app/src/main/java/com/kotlinisgood/boomerang/database/converter/Converter.kt
  app/src/main/java/com/kotlinisgood/boomerang/database/dao/AudioMemoDao.kt
  app/src/main/java/com/kotlinisgood/boomerang/database/entity/AudioMemo.kt
  app/src/main/java/com/kotlinisgood/boomerang/di/DatabaseModule.kt
  app/src/main/java/com/kotlinisgood/boomerang/repository/AppRepository.kt
  app/src/main/java/com/kotlinisgood/boomerang/repository/local/LocalDataSource.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/audiorecord/Audio.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/audiorecord/AudioRecordSecondFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/audiorecord/AudioRecordViewModel.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/audiorecord/SelfReference.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/audiorecord/VoiceRecordFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/voicerecord/Voice.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/voicerecord/VoiceRecordViewModel.kt
  app/src/main/res/layout/fragment_voice_record_second.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#79 [음성 메모 작성 화면] DB 데이터 저장
  app/src/main/java/com/kotlinisgood/boomerang/ui/audiorecord/AudioRecordFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/audiorecord/AudioRecordViewModel.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/audiorecord/VoiceRecordFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/util/Constant.kt
  app/src/main/res/layout/fragment_audio_record.xml
  app/src/main/res/layout/fragment_voice_record.xml
  app/src/main/res/navigation/navigation.xml
Labels: 기능 추가

#81 [메모 화면] 모두의 메모 공유 기능 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/Encoder.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/VideoDoodleFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videoedit/VideoEditFragment.kt
  app/src/main/res/layout/fragment_video_edit.xml
  app/src/main/res/xml/filepaths.xml
Labels: bug, 기능 추가

#83 [음성 메모 작성 화면] 1차 기능 구현 완료 #59 #67
  app/src/main/java/com/kotlinisgood/boomerang/ui/audiorecord/AudioRecordFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/audiorecord/AudioRecordViewModel.kt
  app/src/main/res/layout/fragment_audio_record.xml
Labels: 기능 추가

#87 [음성 메모 화면] 화면에서 음성 텍스트를 확인, 텍스트를 통한 시간이동, 파일 재생이 가능하다 #61 #62 #63
  app/src/main/java/com/kotlinisgood/boomerang/ui/audiomemo/AudioMemoAdapter.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/audiomemo/AudioMemoFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/audiomemo/AudioMemoViewModel.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/audiomemo/TimeSeriesText.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/audiorecord/AudioRecordFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/audiorecord/AudioRecordViewModel.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/home/HomeFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/util/BindingUtil.kt
  app/src/main/res/drawable/image_audio.png
  app/src/main/res/layout/fragment_audio_memo.xml
  app/src/main/res/layout/item_rv_audio_memo_recognized_text.xml
  app/src/main/res/menu/menu_fragment_home_speed_dial.xml
  app/src/main/res/navigation/navigation.xml
  app/src/main/res/values/strings.xml
Labels: 기능 추가

#90 [음성 메모 화면] 음성에 맞는 텍스트 강조 #89
  app/src/main/java/com/kotlinisgood/boomerang/ui/audiomemo/AudioMemoAdapter.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/audiomemo/AudioMemoFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/audiomemo/AudioMemoViewModel.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/audiomemo/TimeSeriesText.kt
  app/src/main/java/com/kotlinisgood/boomerang/util/BindingUtil.kt
  app/src/main/res/layout/item_rv_audio_memo_recognized_text.xml
  app/src/main/res/values/colors.xml
Labels: 기능 추가

#99 [음성 메모 작성 화면] 인식된 음성이 없을 때 예외처리
  app/src/main/java/com/kotlinisgood/boomerang/ui/audiorecord/AudioRecordFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/audiorecord/AudioRecordViewModel.kt
Labels: 기능 추가

#100 Bugfix: Wee4, 최종 데모 버전 완성
  app/src/main/java/com/kotlinisgood/boomerang/ui/audiorecord/AudioRecordFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/audiorecord/AudioRecordViewModel.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/memo/MemoFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/VideoDoodleFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodlelight/VideoDoodleLightFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videoedit/VideoEditFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videomodifylight/VideoModifyLightFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videoselection/VideoSelectionFragment.kt
Labels: bug

#118 [Feat] 키보드 UX 개선
  app/src/main/java/com/kotlinisgood/boomerang/MainActivity.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/home/HomeFragment.kt
  app/src/main/res/layout/fragment_video_edit.xml
Labels: enhancement

#119 [메모 화면] 음성, 동영상 메모 화면에 삭제 기능 추가
  app/src/main/java/com/kotlinisgood/boomerang/repository/AppRepository.kt
  app/src/main/java/com/kotlinisgood/boomerang/repository/local/LocalDataSource.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/audiomemo/AudioMemoFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/audiomemo/AudioMemoViewModel.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodlelight/VideoDoodleLightFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videomemo/VideoMemoFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videomemo/VideoMemoViewModel.kt
  app/src/main/res/drawable-anydpi/ic_dark_trashcan.xml
  app/src/main/res/drawable-hdpi/ic_dark_trashcan.png
  app/src/main/res/drawable-mdpi/ic_dark_trashcan.png
  app/src/main/res/drawable-xhdpi/ic_dark_trashcan.png
  app/src/main/res/drawable-xxhdpi/ic_dark_trashcan.png
  app/src/main/res/layout/fragment_video_memo.xml
  app/src/main/res/menu/menu_fragment_audio_memo.xml
  app/src/main/res/menu/menu_fragment_video_memo.xml
  app/src/main/res/navigation/navigation.xml
  app/src/main/res/values/strings.xml
Labels: 기능 추가

#120 [메모 목록 화면] Audio memo 뷰홀더 추가
  app/src/main/java/com/kotlinisgood/boomerang/ui/home/HomeAdapter.kt
  app/src/main/java/com/kotlinisgood/boomerang/util/BindingUtil.kt
  app/src/main/res/layout/item_rv_home_show_audio.xml
Labels: enhancement

#122 [동영상 메모 화면] 뒤로가기를 버튼을 누르면 뒤로 간다 #121
  app/src/main/java/com/kotlinisgood/boomerang/ui/videomemo/VideoMemoFragment.kt
Labels: 기능 추가

#123 [모두의 메모 화면] 생명 주기에 따라 작동하도록 개선, 기능 추가
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/VideoDoodleFragment.kt
  app/src/main/res/drawable/ic_delete.xml
  app/src/main/res/layout/fragment_video_doodle.xml
Labels: bug, 기능 추가

#127 [오픈소스 라이선스 화면] 오픈소스 라이선스 표시 화면 구현
  app/build.gradle
  app/src/main/java/com/kotlinisgood/boomerang/ui/home/HomeFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/VideoDoodleFragment.kt
  app/src/main/res/layout/fragment_video_doodle.xml
  build.gradle
Labels: bug, 기능 추가

#136 [Dimen] dimen.xml 생성 및 xml 파일 dimen으로 대체 #135
  app/src/main/res/layout/fragment_audio_memo.xml
  app/src/main/res/layout/fragment_audio_record.xml
  app/src/main/res/layout/fragment_video_doodle.xml
  app/src/main/res/layout/fragment_video_doodle_light.xml
  app/src/main/res/layout/fragment_video_edit.xml
  app/src/main/res/layout/fragment_video_memo.xml
  app/src/main/res/layout/fragment_video_modify_light.xml
  app/src/main/res/layout/fragment_video_selection.xml
  app/src/main/res/layout/header_navigation_drawer.xml
  app/src/main/res/layout/item_rv_audio_memo_recognized_text.xml
  app/src/main/res/layout/item_rv_home_show_audio.xml
  app/src/main/res/layout/item_rv_home_show_videos.xml
  app/src/main/res/values/dimen.xml
Labels: enhancement

#138 [메모 목록 화면] 드로어에서 메모 타입 선택 기능 구현
  app/src/main/java/com/kotlinisgood/boomerang/database/dao/MediaMemoDao.kt
  app/src/main/java/com/kotlinisgood/boomerang/repository/AppRepository.kt
  app/src/main/java/com/kotlinisgood/boomerang/repository/local/LocalDataSource.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/home/HomeFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/home/HomeViewModel.kt
Labels: 기능 추가

#140 [음성 메모 작성 화면] 버튼위치를 툴바로 이동
  app/build.gradle
  app/src/main/java/com/kotlinisgood/boomerang/ui/audiorecord/AudioRecordFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/audiorecord/AudioRecordViewModel.kt
  app/src/main/res/drawable-anydpi/ic_mic.xml
  app/src/main/res/drawable-anydpi/ic_save.xml
  app/src/main/res/drawable-hdpi/ic_mic.png
  app/src/main/res/drawable-hdpi/ic_save.png
  app/src/main/res/drawable-mdpi/ic_mic.png
  app/src/main/res/drawable-mdpi/ic_save.png
  app/src/main/res/drawable-xhdpi/ic_mic.png
  app/src/main/res/drawable-xhdpi/ic_save.png
  app/src/main/res/drawable-xxhdpi/ic_mic.png
  app/src/main/res/drawable-xxhdpi/ic_save.png
  app/src/main/res/layout/fragment_audio_record.xml
  app/src/main/res/menu/menu_fragment_audio_record.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: enhancement

#139 [공통] 테마 색상 지정
  app/src/main/java/com/kotlinisgood/boomerang/ui/home/HomeAdapter.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/home/HomeFragment.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_video_memo.xml
  app/src/main/res/menu/menu_fragment_home_speed_dial.xml
  app/src/main/res/menu/navigation_drawer_memo_type.xml
  app/src/main/res/values-night-v23/themes.xml
  app/src/main/res/values-v23/themes.xml
  app/src/main/res/values/colors.xml
Labels: 기능 추가

#142 [음성 메모 작성 화면] 제목 EditText 크기 조절
  app/src/main/res/layout/fragment_audio_record.xml
Labels: enhancement

#144 [Refactor] Throttle 적용
  app/src/main/java/com/kotlinisgood/boomerang/ui/audiomemo/AudioMemoFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/audiorecord/AudioRecordFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/home/HomeFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/VideoDoodleFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodlelight/VideoDoodleLightFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videoedit/VideoEditFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videomemo/VideoMemoFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videoselection/VideoSelectionFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/util/Constant.kt
  app/src/main/res/layout/fragment_audio_record.xml
Labels: enhancement

#146 [Video Screen] Player와 Player Control 뷰 분리
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodlelight/VideoDoodleLightFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videoedit/VideoEditFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videomemo/VideoMemoFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videomodifylight/VideoModifyLightFragment.kt
  app/src/main/res/layout/fragment_video_doodle_light.xml
  app/src/main/res/layout/fragment_video_edit.xml
  app/src/main/res/layout/fragment_video_memo.xml
  app/src/main/res/layout/fragment_video_modify_light.xml
Labels: UI📱

#153 [모두의 메모]리팩터링, 버그 수정
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/Texture2dProgram.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/VideoDoodleFragment.kt
Labels: bug

#155 [Bugfix] Uri 대응
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/VideoDoodleFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodlelight/VideoDoodleLightFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videoedit/VideoEditFragment.kt
Labels: bug

#156 [Feat] SplashScreen 추가
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kotlinisgood/boomerang/MainActivity.kt
  app/src/main/res/drawable/ic_android_logo.xml
  app/src/main/res/values/themes.xml
Labels: UI📱

#158 [bugfix] 이전에 생성된 파일과 이후에 생성된 파일 간에 update를 위해 분기처리 적용
  app/src/main/java/com/kotlinisgood/boomerang/di/DatabaseModule.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/home/HomeAdapter.kt
Labels: bug

#160 [모두의 메모 화면] 미디어 플레이어 뷰 개선
  app/src/main/java/com/kotlinisgood/boomerang/ui/home/HomeFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/VideoDoodleFragment.kt
  app/src/main/res/drawable/ic_doodle_pause.xml
  app/src/main/res/drawable/ic_doodle_play.xml
  app/src/main/res/layout/fragment_video_doodle.xml
Labels: UI📱

#162 [bugfix] Inflate 중복 메뉴
  app/src/main/java/com/kotlinisgood/boomerang/ui/home/HomeFragment.kt
Labels: bug

#163 [Refactor] RxJava dispose 추가 및 dataBinding nullable로 변경
  app/src/main/java/com/kotlinisgood/boomerang/ui/audiomemo/AudioMemoFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/audiorecord/AudioRecordFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/home/HomeFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/home/HomeViewModel.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/VideoDoodleFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodlelight/VideoDoodleLightFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videoedit/VideoEditFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videomemo/VideoMemoFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videomodifylight/VideoModifyLightFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videoselection/VideoSelectionFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/util/Constant.kt
Labels: enhancement

#165 build: increase version 1 to 2
  app/build.gradle
Labels: version

#168 [모두의 메모] 인코더 리팩터링, 메모 재생 화면에 공유하기 기능 추가
  app/src/main/java/com/kotlinisgood/boomerang/ui/home/HomeFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/AspectFrameLayout.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/CircularEncoderBuffer.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/Egl.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/EglWindowSurface.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/Encoder.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/VideoDoodleFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/VideoDoodleViewModel.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videomemo/VideoMemoFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videomodifylight/VideoModifyLightFragment.kt
  app/src/main/res/layout/fragment_video_doodle.xml
  app/src/main/res/menu/menu_fragment_video_memo.xml
  app/src/main/res/navigation/navigation.xml
Labels: bug, 기능 추가

#170 [Refactor] color and theme #169
  app/src/main/java/com/kotlinisgood/boomerang/ui/home/HomeFragment.kt
  app/src/main/res/layout/fragment_audio_record.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values-night-v23/themes.xml
  app/src/main/res/values-night/color.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values-v23/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: UI📱

#174 [Refactor] 오디오 화면 및 다크모드 및 관련된 파일
  app/src/main/java/com/kotlinisgood/boomerang/model/Video.kt
  app/src/main/java/com/kotlinisgood/boomerang/repository/SharedPrefDataSource.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/audiomemo/AudioMemoFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/audiorecord/Audio.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/audiorecord/AudioRecordFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/audiorecord/AudioRecordViewModel.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/home/HomeViewModel.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/home/OrderState.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/home/bottomsheet/BottomSheetFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/home/bottomsheet/BottomSheetFragmentViewModel.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videoselection/VideoGallery.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videoselection/VideoSelectionFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/util/Constant.kt
  app/src/main/java/com/kotlinisgood/boomerang/util/StringUtil.kt
  app/src/main/res/drawable/background_rb_black.xml
  app/src/main/res/drawable/background_rb_black_selected.xml
  app/src/main/res/drawable/background_rb_black_unselected.xml
  app/src/main/res/drawable/background_rb_blue_selected.xml
  app/src/main/res/drawable/background_rb_green_selected.xml
  app/src/main/res/drawable/background_rb_red_selected.xml
  app/src/main/res/drawable/background_rb_yellow_selected.xml
  app/src/main/res/layout/fragment_audio_memo.xml
  app/src/main/res/layout/fragment_audio_record.xml
  app/src/main/res/layout/fragment_video_selection.xml
  app/src/main/res/layout/item_rv_home_show_audio.xml
  app/src/main/res/layout/item_rv_home_show_videos.xml
  app/src/main/res/values/strings.xml
Labels: Refactor

#175 [Refactor] VideoEdit
  app/src/main/java/com/kotlinisgood/boomerang/ui/videomemo/VideoMemoFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videosave/AlphaViewFactory.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videosave/VideoSaveFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videosave/VideoSaveViewModel.kt
  app/src/main/res/layout/fragment_video_save.xml
  app/src/main/res/navigation/navigation.xml
  app/src/main/res/values/strings.xml
Labels: Refactor

#176 [모두의 메모] 화면 비율에 맞게 출력, 린트 검사 결과 수정
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/AspectFrameLayout.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/DrawColor.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/Drawable2d.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/Egl.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/EglWindowSurface.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/FullFrameRect.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/GlUtil.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/Texture2dProgram.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/VideoDoodleFragment.kt
  app/src/main/res/layout/fragment_video_doodle.xml
Labels: bug, Refactor

#178 [Refactor] Video Memo 코드 리팩토링 #177
  app/src/main/java/com/kotlinisgood/boomerang/ui/audiomemo/AudioMemoFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videomemo/VideoMemoFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videomemo/VideoMemoViewModel.kt
  app/src/main/res/layout/fragment_audio_memo.xml
  app/src/main/res/layout/fragment_audio_record.xml
  app/src/main/res/layout/fragment_video_memo.xml
  app/src/main/res/values/strings.xml
Labels: Refactor

#179 [Refactor] 나만의 메모 수정 리팩토링 및 메모 저장 화면 리팩토링
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodlelight/VideoDoodleLightFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videomemo/VideoMemoFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videomodifylight/VideoModifyLightFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videomodifylight/VideoModifyLightViewModel.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videosave/VideoSaveFragment.kt
  app/src/main/res/layout/fragment_video_modify_light.xml
  app/src/main/res/values/strings.xml
Labels: Refactor

#183 [Refactor] 린트 일부 수정
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kotlinisgood/boomerang/MemoApplication.kt
  app/src/main/java/com/kotlinisgood/boomerang/di/DatabaseModule.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/audiomemo/AudioMemoAdapter.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/audiomemo/AudioMemoFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/audiomemo/AudioMemoViewModel.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/audiorecord/AudioRecordFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/audiorecord/SelfReference.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/VideoDoodleFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videomemo/VideoMemoFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videoselection/VideoSelectionAdapter.kt
  app/src/main/java/com/kotlinisgood/boomerang/util/UriUtil.kt
  app/src/main/res/drawable/ic_baseline_pause_24.xml
  app/src/main/res/drawable/ic_baseline_play_arrow_24.xml
  app/src/main/res/drawable/ic_code.xml
  app/src/main/res/drawable/ic_delete.xml
  app/src/main/res/layout/exo_player_control_view.xml
  app/src/main/res/layout/fragment_video_doodle.xml
  app/src/main/res/menu/menu_fragment_audio_record.xml
  app/src/main/res/raw/boomerang_orange.json
  app/src/main/res/values-night-v23/themes.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values-v23/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/backup_rules.xml
  app/src/main/res/xml/media_capabilities.xml
  build.gradle
Labels: Refactor

#184 [Refactor] 모두의 메모, 메모 목록 화면 리팩터링
  app/src/main/java/com/kotlinisgood/boomerang/ui/home/HomeAdapter.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/home/HomeFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/home/HomeViewModel.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/home/OrderState.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/home/bottomsheet/BottomSheetFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/home/bottomsheet/BottomSheetFragmentViewModel.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/oss/OssFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/AspectFrameLayout.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/Drawable2d.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/Egl.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/EglWindowSurface.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/Encoder.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/FullFrameRect.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/FullFrameRectangle.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/GlUtil.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/Program.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/RectangleVertex.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/Texture2dProgram.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/VideoDoodleFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/VideoDoodleViewModel.kt
  app/src/main/java/com/kotlinisgood/boomerang/ui/videodoodle/WindowSurface.kt
  app/src/main/res/layout/fragment_bottom_sheet.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_oss.xml
  app/src/main/res/layout/fragment_video_doodle.xml
  app/src/main/res/layout/item_rv_home_show_audio.xml
  app/src/main/res/layout/item_rv_home_show_videos.xml
  app/src/main/res/navigation/navigation.xml
  app/src/main/res/values/strings.xml
Labels: Refactor

#186 Refactor: 린트 해결 #182
  app/src/main/java/com/kotlinisgood/boomerang/ui/home/HomeFragment.kt
  app/src/main/java/com/kotlinisgood/boomerang/util/CustomLoadingDialog.kt
  app/src/main/res/layout/exo_player_control_view.xml
  app/src/main/res/menu/menu_fragment_home_speed_dial.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/dimen.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: Refactor

#187 [Refactor] 사용하지 않는 문자열 제거
  app/src/main/java/com/kotlinisgood/boomerang/ui/setting/SettingFragment.kt
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/layout/header_navigation_drawer.xml
  app/src/main/res/menu/navigation_drawer_memo_type.xml
  app/src/main/res/navigation/navigation.xml
  app/src/main/res/values/strings.xml
Labels: Refactor
